name: "CIFAR10-ResNet"

dataloader:
  base_dataloader:
    batch_size: 64

training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.1

  optimizer: "sgd"
  optimizer_cfg:
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler:
    name: "cosine"
    args: {}
    cfg:
      interval: "epoch"

  metrics:
    loss:
      when: "trn,val,test"
      name: "MeanMetric"
      file: "torchmetrics"
      update:
        value: "cls_loss"
    confusion_matrix:
      frequency: { "trn": 50 }
      when: "trn,val,test"
      name: "ConfusionMatrix"
      file: "torchmetrics"
      args:
        num_classes: 5
      update:
        preds: "logits"
        target: "y"
    accuracy:
      when: "trn,val,test"
      name: "Accuracy"
      file: "torchmetrics"
      update:
        preds: "logits"
        target: "y"

callbacks:
  - name: ModelCheckpoint
    file: lightning
    args:
      monitor: "epoch_val/accuracy"
      mode: "max"
      save_last: True
      save_top_k: 5
  - name: "LearningRateMonitor"
    file: "lightning"
    args:
      logging_interval: "epoch"

model:
  backbone:
    cfg:
      low_res: True
  modules:
    classifier:
      name: ClassificationHead
      input: "output"
      args:
        reduction: "gap"
        in_features: 512
        dropout: 0.2
        num_classes: 10
        return_logits: True # return logits instead of softmax probability.
    loss_fn:
      name: "CrossEntropyLoss"

wandb:
  project: "CIFAR10-classification"
