name: "CIFAR10-ResNet"
training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.1
  batch_size: 64

  optimizer: "sgd"
  optimizer_cfg:
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler: "cosine"
  lr_scheduler_cfg: {}

  metrics:
    loss:
      when: "trn,val,test"
      name: "MeanMetric"
      file: "torchmetrics"
      update:
        value: "loss"
    confusion_matrix:
      when: "trn,val,test"
      name: "ConfusionMatrix"
      file: "torchmetrics"
      args:
        num_classes: 10
      update:
        preds: "pred"
        target: "y"
    accuracy:
      when: "trn,val,test"
      name: "Accuracy"
      file: "torchmetrics"
      update:
        preds: "pred"
        target: "y"

validation:
  batch_size: 64

callbacks:
  - name: ModelCheckpoint
    file: lightning
    args:
      monitor: "epoch_val/accuracy"
      mode: "max"
      save_last: True
      save_top_k: 5
  - name: "LearningRateMonitor"
    file: "lightning"
    args:
      logging_interval: "epoch"

model:
  backbone:
    cfg:
      low_res: True
  modules:
    classifier:
      name: ClassificationHead
      input: "output"
      args:
        reduction: "gap"
        in_features: 512
        dropout: 0.2
        num_classes: 10
        return_logits: True # return logits instead of softmax probability.
    loss_fn:
      name: "CrossEntropyLoss"


wandb:
  project: "CIFAR10-classification"
