model:
  backbone:
    TYPE: "timm"
    ID: "vit_base_patch16_224_miil_in21k"
    cfg:
      pretrained: True
    out_features: 768

# this is configured for classification, but please remove the GAP layer for other subtasks.
model:
  heads:
    classifier:
      cfg:
        reduction: "none"
        in_features: 768
