# implement mixup using FastCollateMixup implemented in timm
dataloader:
  trn:
    collate_fn:
      name: "FastCollateMixup"
      args:
        mixup_alpha: 1.
        cutmix_alpha: 0.  # no cutmix
        cutmix_minmax: null
        prob: 1.0
        switch_prob: 0.5
        mode: 'batch'
        correct_lam: True
        label_smoothing: 0.0
        num_classes: 1000

