# implement fast collate mixup implemented in timm
# both mixup & cutmix are active, hyperparameters are equal as described in:
# Solving ImageNet: a Unified Scheme for Training any Backbone to Top Results, 2022
dataloader:
  trn:
    collate_fn:
      name: "FastCollateMixup"
      args:
        mixup_alpha: .8
        cutmix_alpha: 1.0
        cutmix_minmax: null
        prob: 1.0
        switch_prob: 0.5
        mode: "batch"
        correct_lam: True
        label_smoothing: 0.1
        num_classes: 1000
model:
  modules:
    loss_fn:
      name: "SoftTargetCrossEntropy"
