---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown] # For line breaks.
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: local
    # According to
    # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html#pre-commit-integration,
    # the pylint hook only accepts local repo.
    # So you need to install pylint in local environment first.
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - --rcfile=linting/.pylintrc

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --config=linting/.flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --settings-path=linting/.isort.cfg

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args:
          - --install-types
          - --ignore-missing-imports
          - --config-file=linting/.mypy.ini

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [yaml, json]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args:
          - --config=linting/.markdownlint.yml
          - --fix # Fix basic errors
