model:
  tta:
    name: "ClassificationTTAWrapper"
    args:
      merge_mode: "mean"
      transforms:
        - name: "HorizontalFlip"
        - name: "Rotation"
          args: 
            angles:
              - 0
              - 30
              - 60
              - 90
              - 120
              - 150 
              - 180
              - 210
              - 240
              - 270
              - 300
              - 330
