auto_scale_lr:
  base_batch_size: 16
  enable: false
checkpoint_config:
  interval: 1
custom_hooks:
  - type: NumClassCheckHook
data:
  samples_per_gpu: 2
  test:
    ann_file: data/coco/annotations/instances_val2017.json
    img_prefix: data/coco/val2017/
    pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
          - 1333
          - 800
        transforms:
          - keep_ratio: true
            type: Resize
          - type: RandomFlip
          - mean:
              - 103.53
              - 116.28
              - 123.675
            std:
              - 1.0
              - 1.0
              - 1.0
            to_rgb: false
            type: Normalize
          - size_divisor: 32
            type: Pad
          - keys:
              - img
            type: ImageToTensor
          - keys:
              - img
            type: Collect
        type: MultiScaleFlipAug
    type: CocoDataset
  train:
    dataset:
      ann_file: data/coco/annotations/instances_train2017.json
      img_prefix: data/coco/train2017/
      pipeline:
        - type: LoadImageFromFile
        - type: LoadAnnotations
          with_bbox: true
        - img_scale:
            - - 1333
              - 640
            - - 1333
              - 800
          keep_ratio: true
          multiscale_mode: range
          type: Resize
        - flip_ratio: 0.5
          type: RandomFlip
        - mean:
            - 103.53
            - 116.28
            - 123.675
          std:
            - 1.0
            - 1.0
            - 1.0
          to_rgb: false
          type: Normalize
        - size_divisor: 32
          type: Pad
        - type: DefaultFormatBundle
        - keys:
            - img
            - gt_bboxes
            - gt_labels
          type: Collect
      type: CocoDataset
    times: 3
    type: RepeatDataset
  val:
    ann_file: data/coco/annotations/instances_val2017.json
    img_prefix: data/coco/val2017/
    pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
          - 1333
          - 800
        transforms:
          - keep_ratio: true
            type: Resize
          - type: RandomFlip
          - mean:
              - 103.53
              - 116.28
              - 123.675
            std:
              - 1.0
              - 1.0
              - 1.0
            to_rgb: false
            type: Normalize
          - size_divisor: 32
            type: Pad
          - keys:
              - img
            type: ImageToTensor
          - keys:
              - img
            type: Collect
        type: MultiScaleFlipAug
    type: CocoDataset
  workers_per_gpu: 2
data_root: data/coco/
dataset_type: CocoDataset
dist_params:
  backend: nccl
evaluation:
  interval: 1
  metric: bbox
img_norm_cfg:
  mean:
    - 103.53
    - 116.28
    - 123.675
  std:
    - 1.0
    - 1.0
    - 1.0
  to_rgb: false
load_from: null
log_config:
  hooks:
    - type: TextLoggerHook
  interval: 50
log_level: INFO
lr_config:
  policy: step
  step:
    - 9
    - 11
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.001
model:
  backbone:
    depth: 50
    frozen_stages: 1
    init_cfg:
      checkpoint: open-mmlab://detectron2/resnet50_caffe
      type: Pretrained
    norm_cfg:
      requires_grad: false
      type: BN
    norm_eval: true
    num_stages: 4
    out_indices:
      - 0
      - 1
      - 2
      - 3
    style: caffe
    type: ResNet
  neck:
    in_channels:
      - 256
      - 512
      - 1024
      - 2048
    num_outs: 5
    out_channels: 256
    type: FPN
  pretrained: null
  roi_head:
    bbox_head:
      bbox_coder:
        target_means:
          - 0.0
          - 0.0
          - 0.0
          - 0.0
        target_stds:
          - 0.1
          - 0.1
          - 0.2
          - 0.2
        type: DeltaXYWHBBoxCoder
      fc_out_channels: 1024
      in_channels: 256
      loss_bbox:
        loss_weight: 1.0
        type: L1Loss
      loss_cls:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: false
      num_classes: 80
      reg_class_agnostic: false
      roi_feat_size: 7
      type: Shared2FCBBoxHead
    bbox_roi_extractor:
      featmap_strides:
        - 4
        - 8
        - 16
        - 32
      out_channels: 256
      roi_layer:
        output_size: 7
        sampling_ratio: 0
        type: RoIAlign
      type: SingleRoIExtractor
    pretrained: null
    test_cfg:
      max_per_img: 100
      nms:
        iou_threshold: 0.5
        type: nms
      score_thr: 0.05
    train_cfg:
      assigner:
        ignore_iof_thr: -1
        match_low_quality: false
        min_pos_iou: 0.5
        neg_iou_thr: 0.5
        pos_iou_thr: 0.5
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: true
        neg_pos_ub: -1
        num: 512
        pos_fraction: 0.25
        type: RandomSampler
    type: StandardRoIHead
  rpn_head:
    anchor_generator:
      ratios:
        - 0.5
        - 1.0
        - 2.0
      scales:
        - 8
      strides:
        - 4
        - 8
        - 16
        - 32
        - 64
      type: AnchorGenerator
    bbox_coder:
      target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      target_stds:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      type: DeltaXYWHBBoxCoder
    feat_channels: 256
    in_channels: 256
    loss_bbox:
      loss_weight: 1.0
      type: L1Loss
    loss_cls:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: true
    type: RPNHead
  test_cfg:
    rcnn:
      max_per_img: 100
      nms:
        iou_threshold: 0.5
        type: nms
      score_thr: 0.05
    rpn:
      max_per_img: 1000
      min_bbox_size: 0
      nms:
        iou_threshold: 0.7
        type: nms
      nms_pre: 1000
  train_cfg:
    rcnn:
      assigner:
        ignore_iof_thr: -1
        match_low_quality: false
        min_pos_iou: 0.5
        neg_iou_thr: 0.5
        pos_iou_thr: 0.5
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: true
        neg_pos_ub: -1
        num: 512
        pos_fraction: 0.25
        type: RandomSampler
    rpn:
      allowed_border: -1
      assigner:
        ignore_iof_thr: -1
        match_low_quality: true
        min_pos_iou: 0.3
        neg_iou_thr: 0.3
        pos_iou_thr: 0.7
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: false
        neg_pos_ub: -1
        num: 256
        pos_fraction: 0.5
        type: RandomSampler
    rpn_proposal:
      max_per_img: 1000
      min_bbox_size: 0
      nms:
        iou_threshold: 0.7
        type: nms
      nms_pre: 2000
  type: FasterRCNN
mp_start_method: fork
opencv_num_threads: 0
optimizer:
  lr: 0.02
  momentum: 0.9
  type: SGD
  weight_decay: 0.0001
optimizer_config:
  grad_clip: null
resume_from: null
runner:
  max_epochs: 12
  type: EpochBasedRunner
test_pipeline:
  - type: LoadImageFromFile
  - flip: false
    img_scale:
      - 1333
      - 800
    transforms:
      - keep_ratio: true
        type: Resize
      - type: RandomFlip
      - mean:
          - 103.53
          - 116.28
          - 123.675
        std:
          - 1.0
          - 1.0
          - 1.0
        to_rgb: false
        type: Normalize
      - size_divisor: 32
        type: Pad
      - keys:
          - img
        type: ImageToTensor
      - keys:
          - img
        type: Collect
    type: MultiScaleFlipAug
train_pipeline:
  - type: LoadImageFromFile
  - type: LoadAnnotations
    with_bbox: true
  - img_scale:
      - - 1333
        - 640
      - - 1333
        - 800
    keep_ratio: true
    multiscale_mode: range
    type: Resize
  - flip_ratio: 0.5
    type: RandomFlip
  - mean:
      - 103.53
      - 116.28
      - 123.675
    std:
      - 1.0
      - 1.0
      - 1.0
    to_rgb: false
    type: Normalize
  - size_divisor: 32
    type: Pad
  - type: DefaultFormatBundle
  - keys:
      - img
      - gt_bboxes
      - gt_labels
    type: Collect
workflow:
  - - train
    - 1
