dataset:
  TYPE: "torchvision"
  NAME: "CIFAR10"
  base_transform: ["ToTensor"]
  dataset_base_config: 
    root: "./cifar10"
    download: True
  dataset_subset_config:
    trn:
      train: True
    val:
      train: False
  