# base config for training.
name: "default-experiment"
VERBOSE: "DEFAULT"
DEBUG_MODE: False

debug:
  network_summary:
    input_shape: [3, 224, 224]
  view_train_augmentation:
    save_to: "vis/training_samples.png"
    subplot_dim: [4, 4]
    imsize: 5

trainer:
  gpus: [0] # [0] for training in Google COLAB.
  accelerator: "dp"
  accumulate_grad_batches: 1
  sync_batchnorm: True
  check_val_every_n_epoch: 5
  precision: 32

dataloader:
  base_dataloader:
    num_workers: 8
    pin_memory: True
    shuffle: True
    prefetch_factor: 2
  trn:
    shuffle: True
  val:
    shuffle: False
    drop_last: False
