name: "CowPrediction"

dataset:
  MODE: "custom"
  NAME: "CIFAR10"
  trn_size: 9000
  val_size: 1000
  # list of parameters used when using `data.dataset.torchvision_dataset` to load `torchvision.datasets`
  dataset_base_cfg:
    seed: 42
    split: 1000
  dataset_subset_cfg:
    trn:
      subset: "train"
    val:
      subset: "train"

# Data augmentation for FasterRCNN is adopted from:
# https://github.com/facebookresearch/maskrcnn-benchmark/blob/main/maskrcnn_benchmark/data/transforms/build.py
# https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/roi_data_layer/roibatchLoader.py
transform:
  [
    [
      "trn",
      [
        { "name": "TorchTransforms", "args": { "NAME": "RandomHorizontalFlip" } },
        { "name": "TorchTransforms", "args": { "NAME": "RandomVerticalFlip" } },
        {
          "name": "TorchTransforms", 
          "args": { "NAME": "RandAugment", "ARGS": {"num_ops": 2,  "magnitude": 9} }
        },
      ],
    ],
    [
      "trn,val",
      [
        { "name": "ClassificationLabelEncoder" },
      ],
    ],

    [
      "trn,val,pred",
      [
        { "name": "Resize", "args": { "size": [224, 224] } },
        { "name": "ToTensor", "args": {} },
        {
          "name": "Normalize",
          "args": { "mean": [0.25252014, 0.12918881, 0.12411932], "std": [0.24537923, 0.17195621, 0.17269008] },
        },
      ],
    ],
  ]

model:
  backbone:
    TYPE: "timm"
    ID: "resnet18"
    cfg:
      pretrained: False
    out_features: 512
  heads:
    classifier:
      ID: ClassificationHead
      input: "output"
      cfg:
        reduction: "gap"
        in_features: 512
        dropout: 0.5
        num_classes: 5
        return_logits: True # return logits instead of softmax probability.

training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.1
  batch_size: 64

  optimizer: "adamw"
  optimizer_cfg:
    betas: [0.9, 0.999]
    weight_decay: 0.0005
  lr_scheduler: "cosine"
  lr_scheduler_cfg: {}
  losses:
    label_smoothing: 0.1

validation:
  batch_size: 64
  metrics:

debug:
  network_summary:
    input_shape: [3, 224, 224]

# other useful configs.
wandb:
  project: "cow_grade_prediction_challenge_2022"

const:
  task: "image classification"
  normalization_mean: [0.25252014, 0.12918881, 0.12411932]
  normalization_std: [0.24537923, 0.17195621, 0.17269008]

  label_map:
    - "1++"
    - "1+"
    - "1"
    - "2"
    - "3"
