name: "CowPrediction"

dataset:
  MODE: "custom"
  NAME: "CIFAR10"
  trn_size: 9000
  val_size: 1000
  # list of parameters used when using `data.dataset.torchvision_dataset` to load `torchvision.datasets`
  dataset_base_cfg:
    seed: 42
    split: 1000
  dataset_subset_cfg:
    trn:
      subset: "train"
    val:
      subset: "train"
  initial_transform:
    name: "TupleToClassificationData"

# Data augmentation for FasterRCNN is adopted from:
# https://github.com/facebookresearch/maskrcnn-benchmark/blob/main/maskrcnn_benchmark/data/transforms/build.py
# https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/roi_data_layer/roibatchLoader.py
transform:
  [
    [
      "trn",
      [
        { "name": "Resize", "args": { "size": [224, 224] } },
        {
          "name": "TorchTransforms",
          "args": { "NAME": "RandomHorizontalFlip" },
        },
      ],
    ],
    [
      "trn,val",
      [
        { "name": "ToTensor", "args": {} },
        { "name": "LabelEncoder" },
        {
          "name": "Normalize",
          "args": { "mean": [0.5, 0.5, 0.5], "std": [1, 1, 1] },
        },
      ],
    ],
  ]

model:
  backbone:
    TYPE: "timm"
    ID: "resnet18"
    cfg:
      pretrained: False
    out_features: 512
  heads:
    classifier:
      ID: ClassificationHead
      input: "output"
      cfg:
        reduction: "gap"
        in_features: 512
        dropout: 0.2
        num_classes: 5
        return_logits: True # return logits instead of softmax probability.

training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.1
  batch_size: 64

  optimizer: "sgd"
  optimizer_cfg:
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler: "cosine"
  lr_scheduler_cfg: {}
  losses:

validation:
  batch_size: 64
  metrics:

debug:
  network_summary:
    input_shape: [3, 224, 224]

# other useful configs.
wandb:
  project: "cow_grade_prediction_challenge_2022"

const:
  task: "image classification"
  normalization_mean: [0.5, 0.5, 0.5]
  normalization_std: [1, 1, 1]

  label_map:
    - "1++"
    - "1+"
    - "1"
    - "2"
    - "3"
